theme: jekyll-theme-minimal
title: David Puelz
description: Statistician and professor at The University of Austin (UATX). My research develops computational methods for applied data analysis, especially in business, economics, and the behavioral sciences.
logo: puelz-2.png
url: https://www.davidpuelz.com

exclude:
  - venv/
  - extract_figure.py
  - preview.html
